name: docker build

# 1. Trigger
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    # 2. setup variables
    - uses: FranzDiebold/github-env-vars-action@v2
    - name: Get current date
      id: date
      run: echo "::set-output name=today::$(date +'%Y%m%d')"

    # 3. Checkout code
    - name: Checkout
      uses: actions/checkout@v2

    # 4. Login DockerHub
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 5. setup buildx
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    # 6. Build and Push
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        push: true
        # 7. nameing
        tags: |
          ghcr.io/${{ github.repository_owner  }}/${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}:${{ steps.date.outputs.today }}
          ghcr.io/${{ github.repository_owner  }}/${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}:latest
